### ISSUE TITLE
Position mapping blocks queries

### ISSUE THREAD

**Issue by fabxc** [fabxc/tsdb#1]
A memory block receives series from writers in random order. Based on that it builds the inverted index, which relies on monotonically increasing IDs for each series.
For querying, we want series to be in lexicographic order of their label sets to efficiently merge them between blocks.

For that we have a position mapper, which can reorder an iteration over inverted index efficiently and give us the needed order on querying. Whenever a new series appears the position mapper has to be updated.
Being more strict by default, this is currently checked before querying and the query blocks until the mapper is updated. This guarantees that any series is immediately visible after successful insertion. This causes some queries to respond slowly (sorting hundreds to thousands of label sets may take several seconds) and being severely impacted by environments, where a new series appears every few seconds.

Two points here:
* make updating of the position mapper more efficient. If we insert 1 new series, insertion sort is way more efficient than sorting all series again
* can we make the mapper completely non-blocking, i.e. by maintaining leveled mappings that can be merged in the background?
* consider what consistency guarantees we want to give. Do we really want new series to be immediately queryable once `Commit()` on the insertion returned? Are we fine with a delay of a few seconds? Should queriers block or the writer creating a new series?

@brian-brazil @beorn7

This might be a bit of an abstract issue as its a deeper internal.

**Comment by brian-brazil** [comment]
> Do we really want new series to be immediately queryable once Commit() on the insertion returned?

Yes, it'd cause various oddness in more complex rules if this weren't the case.

**Comment by beorn7** [comment]
Just as a data point: Current storage doesn't guarantee immediate indexing either. The delay is usually low, but there are cases of a longish indexing queue where it takes some seconds to show up. That has never stirred up any confusion, AFAIK.

If the delay goes into the minute range, things might get relevant, though. Problem is that everything scales with the number of series: indexing becomes more expensive,the frequency of index updates increases, and also the number of series that need to be added to the mapping. My experiments suggested 45s re-mapping time with 6M time series right now with the naive implementation. Suggested first step would be to see how much this drops with optimized updates of the mapping. And then think about scaling behavior for 10M or 50M time series (10x approach). If that results in "meh, will never be worse than 5s", I would just accept the delay and not go crazy with more complicated approaches.

**Comment by brian-brazil** [comment]
> If that results in "meh, will never be worse than 5s", I would just accept the delay and not go crazy with more complicated approaches.

That's fine with our current semantics, but not once we have rule groups. One rule may be expecting data from the previous rule to be available.

**Comment by beorn7** [comment]
Oh yeah, rule interdependency will be fun... ;)

Still, rules usually don't create new time series in each run. So in practice, I expect little impact (if the delay is usually smaller than an evaluation cycle). However, scenarios could be crafted that would completely fail with an indexing delay.

**Comment by fabxc** [comment]
Solved by removing the feature. It was an optimization that introduced a lot of problem and, on further evaluation, was not nearly as necessary as anticipated.
